### ISSUE TITLE
monoNFTコントラクトの出品周りの実装

### ISSUE THREAD

**Issue by yu23ki14** [henkaku-center/mono-auction-contract#3]
- tokenId管理の変数
- tokenIdとMonoNFTを紐付けるmapping
を実装する

registerNFT関数を実装する

テストコードを実装する

**Comment by takerunakao** [comment]
取り組みます！

**Comment by geeknees** [comment]
@nfttakerun 

monoNFTの実装は monoNFTBase というブランチでやっているのでご注意ください。

出品の登録は

https://github.com/henkaku-center/mono-auction-contract/blob/feature/monoNFTBase/contracts/MonoNFT.sol#L27

あたりで実装済みで、おそらく出品については

https://github.com/henkaku-center/mono-auction-contract/blob/feature/monoNFTBase/contracts/MonoNFT.sol#L47

ここの ` function submit(uint256 tokenId) external onlyRole(DEFAULT_ADMIN_ROLE) {` でステータス変更することで対応することを想定しているのかなと思っています。

不明点があれば discord 等で確認しながら進められるとありがたいです 🙏
